# Generated by Django 6.1 on 2026-08-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('artista', models.CharField(max_length=150)),
                ('duracao_segundos', models.IntegerField()),
                ('favorita', models.BooleanField(default=False)),
            ],
        ),
    ]
